Repository scoville/re-formidable, pull requests merged in 2021-01, with the labels that each got.

#15 Update dependencies and use re-optic instead of bs-optic
  README.md
  bsconfig.json
  package.json
  yarn.lock
Labels: ready for review

#16 Use re-formidable instead of formidable
  bsconfig.json
  package.json
Labels: ready for review

#18 feat: convert all things to rescript
  example/App.res
  example/Components.re
  example/Components.res
  example/I18n.re
  example/I18n.res
  example/Index.res
  example/Validations.re
  example/Validations.res
  src/Formidable.re
  src/Formidable.res
  src/FormidableEvents.re
  src/FormidableEvents.res
  src/FormidableExtra.re
  src/FormidableExtra.res
  src/FormidableValidations.re
  src/FormidableValidations.res
  tests/Formidable_Test.re
  tests/Formidable_Test.res
  tests/TestHelpers.re
  tests/TestHelpers.res
Labels: question, ready for review

#19 Update re-optic
  yarn.lock
Labels: ready for review

#21 Use arrays instead of lists as they're cleaner and faster in our case
  example/App.res
  example/Components.res
  example/Validations.res
  src/Formidable.res
  src/FormidableExtra.res
  src/FormidableValidations.res
Labels: ready for review

#24 As of today the doc uses @ocaml.doc`
  src/FormidableValidations.res
Labels: ready for review

#25 React types: Drops the OCaml style react.component last remnants
  src/Formidable.res
  src/FormidableValidations.res
Labels: ready for review

#27 Simplify the API and encourage the Functor or runtime ways
  example/App.res
  example/Components.res
  src/Formidable.res
  src/FormidableEvents.res
Labels: ready for review

#28 Improve validation description safety
  example/App.res
  example/Components.res
  example/Validations.res
  src/Formidable.res
  src/FormidableValidations.res
Labels: ready for review

#29 Revert functor arguments order
  example/App.res
  src/Formidable.res
Labels: ready for review

#30 Use a slightly more explicit api surface to define validations without the need for explicit lists
  example/Validations.res
  src/Formidable.res
  src/FormidableValidations.res
Labels: ready for review

#31 Add a setFieldState function to the hook and an example of Async validation
  example/App.res
  example/Components.res
  example/FakeFetch.res
  example/I18n.res
  src/Formidable.res
  tests/Formidable_Test.res
  tests/__snapshots__/Formidable_Test.bs.js.snap
Labels: work in progress

#32 Small reorganization
  src/Formidable.res
Labels: ready for review

#34 Move out handlers logic to make it reactive
  example/App.res
  src/Formidable.res
  src/FormidableEvents.res
  tests/__snapshots__/Formidable_Test.bs.js.snap
Labels: ready for review

#38 Force eq function for error and validation label types
  example/Components.res
  example/I18n.res
  example/Validations.res
  src/Formidable.res
  src/FormidableExtra.res
Labels: question, ready for review
